### create user
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
    "username":"test2@gmail.com",
    "password":"freefreefree"
}

### login

POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
    "username":"test2@gmail.com",
    "password":"freefreefree"
}

### get chats
GET http://127.0.0.1:5000/chat
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2MjkwMzM1LCJleHAiOjE3NTYzNzY3MzV9.QQOnMBIwV4ZumCB3G7SkSnQCMEIvJtDOL27eOxNXu28

### chat
POST http://127.0.0.1:5000/chat
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU2MTY4Mjg1LCJleHAiOjE3NTYyNTQ2ODV9.eTSbLJMOLvXTVvsOLREZ2GpjFmxkRCnTWW8WxJwHC2Y

{
    "chatinput":"hello baby"
}